### ISSUE TITLE
[Feature Request] (Windows) Remove dependence on Winget and UWPs

### ISSUE THREAD

**Issue by ehamawy** [dragoonDorise/EmuDeck#1025]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

EmuDeck Application Feedback

### Elaborate on the feature you would like to see added to EmuDeck.

Some Windows 10/11 versions don't come with The Microsoft Store, Winget, AppInstaller, or the ability to run UWPs at all. These enterprise ltsc branches are used by many companies, as well as enthusists through projects like Tiny10. I thought I'd let yall know the installer doesn't run on these versions.

### Include any websites or links that may support your feature request.

e

**Comment by WingofaGriffin** [comment]
What would you propose be used instead? Has Chocolatey improved over the last few years since I last used it? I've enjoyed Winget personally as it is one less third party dependency to rely on, but I suppose there could be an option to use Winget vs all Chocolatey. Or is something like Scoop better now?

**Comment by dragoonDorise** [comment]
@ehamawy we use winget to install only a few things, does the script just close? do you have an example of the errors?
