### ISSUE TITLE
[Bug Report] - Steam ROM Manager will refuse to parse emulators after new update

### ISSUE THREAD

**Issue by PS2ClassicsVault** [dragoonDorise/EmuDeck#1062]
### Prerequisite Steps

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [x] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

when adding a new emulator like pegasus, it will say invlid configuration skipping and not even parse them to steam

**Comment by Markw27348** [comment]
Same issue

**Comment by gnuloonix** [comment]
Here's how to fix Steam Rom Manager not parsing after the latest Emudeck update. This is without any CLI knowledge, but if you know the CLI you can use sed instead of jdReplace.

Firstly, go to Discover and search for jdReplace. Install it.

Then, make a backup of ~/.config/steam-rom-manager in your home directory, just in case.

Then, open jdReplace, and click browse, and open ".config/steam-rom-manager" and under "Search for" paste:

/run/media/mmcblk0p1/

and under "Replace with", paste:

/home/deck/

Make sure "Search Subdirectories" is checked.

Now click ok.

Now open steam rom manager, it should be fixed.

Screenshot:

https://postimg.cc/D8Fvs7FC

If it doesn't work for you, maybe you have emudeck installed on an sd card, and maybe you should try reversing "Search for" and "Replace with".

Let me know if it fixes it for you.

**Comment by PS2ClassicsVault** [comment]
> Here's how to fix Steam Rom Manager not parsing after the latest Emudeck update. This is without any CLI knowledge, but if you know the CLI you can use sed instead of jdReplace.
> 
> Firstly, go to Discover and search for jdReplace. Install it.
> 
> Then, make a backup of ~/.config/steam-rom-manager in your home directory, just in case.
> 
> Then, open jdReplace, and click browse, and open ".config/steam-rom-manager" and under "Search for" paste:
> 
> /run/media/mmcblk0p1/
> 
> and under "Replace with", paste:
> 
> /home/deck/
> 
> Make sure "Search Subdirectories" is checked.
> 
> Now click ok.
> 
> Now open steam rom manager, it should be fixed.
> 
> Screenshot:
> 
> https://postimg.cc/D8Fvs7FC
> 
> If it doesn't work for you, maybe you have emudeck installed on an sd card, and maybe you should try reversing "Search for" and "Replace with".
> 
> Let me know if it fixes it for you.
> 

Sounds complicated and i have it installed via internal storage

**Comment by dragoonDorise** [comment]
this has been fixed, if you are still having issues do a reset in manage emulators for SRM
