### ISSUE TITLE
[Bug Report] Steam ROM Manager is not working after last update

### ISSUE THREAD

**Issue by DanielMMend** [dragoonDorise/EmuDeck#1064]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

Steam ROM Manager is not showing all of the emulators, just a few... And the few that it shows, are also not working.

It is not importing the games to Steam Library... The issue started today, after the last update

**Comment by SiTWulf** [comment]
Same issue.
Unable to Parse, unable to select some emulators (For example PPSSPP)

**Comment by Arty03** [comment]
i wa sable to manually update the paths but after manually adding to 
NGCube files disapear after adding other roms
RPX roms wiu wont appear 

What i can tell alll of the paths got borked ROMS and Launcher all pointing to a storage  mmcblk0p1 path

**Comment by gnuloonix** [comment]
Here's how to fix Steam Rom Manager not parsing after the latest Emudeck update. This is without any CLI knowledge, but if you know the CLI you can use sed instead of jdReplace.

Firstly, go to Discover and search for jdReplace. Install it.

Then, make a backup of ~/.config/steam-rom-manager in your home directory, just in case.

Then, open jdReplace, and click browse, and open ".config/steam-rom-manager" and under "Search for" paste:

/run/media/mmcblk0p1/

and under "Replace with", paste:

/home/deck/

Make sure "Search Subdirectories" is checked.

Now click ok.

Now open steam rom manager, it should be fixed.

Screenshot:

https://postimg.cc/D8Fvs7FC

If it doesn't work for you, maybe you have emudeck installed on an sd card, and maybe you should try reversing "Search for" and "Replace with".

Let me know if it fixes it for you.

**Comment by DanielMMend** [comment]
@gnuloonix I really dont think I want tô mess with this kind of stuff... Probably will wait for them tô fix It...

Thank you anyway

**Comment by Arty03** [comment]
> Here's how to fix Steam Rom Manager not parsing after the latest Emudeck update. This is without any CLI knowledge, but if you know the CLI you can use sed instead of jdReplace.
> 
> Firstly, go to Discover and search for jdReplace. Install it.
> 
> Then, make a backup of ~/.config/steam-rom-manager in your home directory, just in case.
> 
> Then, open jdReplace, and click browse, and open ".config/steam-rom-manager" and under "Search for" paste:
> 
> /run/media/mmcblk0p1/
> 
> and under "Replace with", paste:
> 
> /home/deck/
> 
> Make sure "Search Subdirectories" is checked.
> 
> Now click ok.
> 
> Now open steam rom manager, it should be fixed.
> 
> Screenshot:
> 
> https://postimg.cc/D8Fvs7FC
> 
> If it doesn't work for you, maybe you have emudeck installed on an sd card, and maybe you should try reversing "Search for" and "Replace with".
> 
> Let me know if it fixes it for you.

yeah not the same for me no steam rom manager on that route or any in that directory

**Comment by gnuloonix** [comment]
> > Here's how to fix Steam Rom Manager not parsing after the latest Emudeck update. This is without any CLI knowledge, but if you know the CLI you can use sed instead of jdReplace.
> > Firstly, go to Discover and search for jdReplace. Install it.
> > Then, make a backup of ~/.config/steam-rom-manager in your home directory, just in case.
> > Then, open jdReplace, and click browse, and open ".config/steam-rom-manager" and under "Search for" paste:
> > /run/media/mmcblk0p1/
> > and under "Replace with", paste:
> > /home/deck/
> > Make sure "Search Subdirectories" is checked.
> > Now click ok.
> > Now open steam rom manager, it should be fixed.
> > Screenshot:
> > https://postimg.cc/D8Fvs7FC
> > If it doesn't work for you, maybe you have emudeck installed on an sd card, and maybe you should try reversing "Search for" and "Replace with".
> > Let me know if it fixes it for you.
> 
> yeah not the same for me no steam rom manager on that route or any in that directory

you didn't follow the instructions properly. read it again

**Comment by Arty03** [comment]
recent 03/07/2024 Update fix issue , but wiiu rpx installed games are sill missing

**Comment by dragoonDorise** [comment]
this has been fixed, if you are still having issues do a reset in manage emulators for SRM

**Comment by HenkoHallows** [comment]
I have the same issue, Uninstalling and reinstalling didn't fix it.

It wont open, nothing happens when i click curtain things in emudeck but i get this when i click SRM in my app menu.

Any emulator i try to open manually says the same thing.
![Screenshot_20241212_180155](https://github.com/user-attachments/assets/dedb712b-dd6d-4818-b6b0-9f882f250a1e)

Started happening after an update. Any idea how to fix it? I'm on Cachy OS btw
