### ISSUE TITLE
enhancement - rpcs3 game update downloader

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#130]
https://github.com/RainbowCookie32/rusty-psn/releases/

Just adds a way to get ps3 update pkg files onto the deck. The game still needs to be provided.

Thoughts?

**Comment by filmcriticbeta** [comment]
Apologies, but you meant RPCS3/PS3 rather than pcsx2/PS2 correct?

- I can see this being quite a useful feature for export users, but it might be too advanced for Joe/Jane Average?
- The gui likely requires modifying the read only partition, so it might be best to stick to cli only and provide some sort of script for batch processing.
- For batch processing one would likely need a method to scape the gameID from the iso/psn package.  That’s trivial for ps1/ps2 disks ( the gameID was saved in the boot.cnf file in the iso, so you can just use strings/grep on the iso to extract it ) but I’m unsure if that can be done for ps3.

**Comment by Godsbane** [comment]
I did, will edit the title

**Comment by Godsbane** [comment]
Tested this.

Gui version works fine.

extract zip, set executable. just worked, and was a handy tool to grab an update. It requires the Title Serial to work.
