### ISSUE TITLE
Yuzu rom directory is not set by default

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#160]
has some random junk from a different mount.

**Comment by Godsbane** [comment]
https://github.com/dragoonDorise/EmuDeck/commit/dedc7cf004fc128cb14e49217813795459340a84

**Comment by AlanMW** [comment]
This can be updated manually by clicking Add New Game Directory, then navigating to the EmuDeck Created ROMs folder. Selecting the folder went inside the folder instead of adding it as a selection when using Dolphin on the Deck. Pressing the back button after going inside the folder allows the folder to be selected and the Game Directory to be updated.
