### ISSUE TITLE
Unable to save config: retroarch.cfg

### ISSUE THREAD

**Issue by baltimoresports** [dragoonDorise/EmuDeck#19]
**Versions**
EmuDeck: 0.14.1, 015.1
RetroArch: 1.10.2
SteamOS: 20220227.3

**Issue Description**
After using the EmuDeck script, I lose the ability to save to the retroarch.cfg config file. After loading a core and rom, I get the following error:

```
Failed saving config to
"/home/deck/.var/app/org.libretro.RetroArch/config/retroarch/retroarch.cfg"
```

**Troubleshooting Steps**
- Issue is replicatable. If you wipe the Steam Deck to factory-default and install via EmuDeck script, you will be unable to save the local config.
- Enabled all file permissions in Flatseal
- Enabled write permissions for others for retroarch.cfg
- Restoring the Deck to factory-default and installing RetroArch first allows you to save the config. After installing EmuDeck, I then lose the ability to save.

**Workaround**

- Install EmuDeck
- Delete the RetroArch Flatpak
- Delete the "/home/deck/.var/app/org.libretro.RetroArch/" folder
- Install RetroArch Flatpak
- Overwrite the retroarch.cfg file with the EmuDeck version
- Manually install cores

**Comment by 0swin** [comment]
This used to work on a previous EmuDeck version.
After reinstalling my Steam Deck for another problem, Retroarch config no longer gets saved.
Also, enabling auto save and auto load on retroarch in the EmuDeck installer is not taken into account anymore.

**Comment by dragoonDorise** [comment]
Ok, this was hard to find the source of the issue.

It turns out it's a RetroArch issue, if the Core you are using has a custom override then you can't save anything to your retroarch.cfg file.

These are the steps I did.

### On a Clean install of RA
I open a GBA game, then I go back to Main Menu > Configuration File > Save Current Configuration.
**Everything works.**

But if I do this:
I open a GBA game, I go to Main Menu > Quick Menu > Overrides > Save Content Directory Overrides.
Then I go back to Main Menu > Configuration File > Save Current Configuration 
**I get the "/home/deck/.var/app/org.libretro.RetroArch/config/retroarch/retroarch.cfg" message**

Since EmuDeck has custom cfg overrides files it fails with almost every system.

I've found a solution, changing the overrides files to .opt from .cfg fixes the issue!

This will be present in the next 0.15.5 version :)

**Comment by Alseenrodelap** [comment]
This issue is still present with the current version so it wasn't fixed in 0.15.5.

**Comment by hhirsch** [comment]
Still happens in 0.17.5 this issue should still be open.

**Comment by dragoonDorise** [comment]
Hi @hhirsch , our opt solution didn’t work, we had to go back to .cfg files that still causes this issue.

RetroArch won’t allow you to save the main config if you are using overrides, since EmuDeck uses directory overrides we advice you to use core overrides so your config won’t be deleted on future updates of EmuDeck

**Comment by dragoonDorise** [comment]
Hi @hhirsch , our opt solution didn’t work, we had to go back to .cfg files that still causes this issue.

RetroArch won’t allow you to save the main config if you are using overrides, since EmuDeck uses directory overrides we advice you to use core overrides so your config won’t be deleted on future updates of EmuDeck

**Comment by hhirsch** [comment]
@dragoonDorise How do core overrides work?

**Comment by Godsbane** [comment]
https://docs.libretro.com/guides/overrides/

Emudeck currently mostly uses Content Directory overrides, specifically, so you need to learn the heirarchy.

Some of this is also documented in https://github.com/dragoonDorise/EmuDeck/wiki/Retroarch

**Comment by hhirsch** [comment]
I tried a core override but it did not work. I just want to get rid of the ugly overlay that covers part of the game.

**Comment by Godsbane** [comment]
Yes again, we use content directory, so you have to save content directory. core is lower priority.

**Comment by hhirsch** [comment]
Thanks so much. This worked. Would it be beneficial if I wrote a bit of documentation in the wiki?

**Comment by Godsbane** [comment]
Any documentation is lovely and appreciated. I started a retroarch wiki article. Please feel free to update / edit. Maybe the current content should be moved to a subcategory, etc.

**Comment by mdeguzis** [comment]
The functions are overridden in many places using built in bash functions they make before launching: https://github.com/dragoonDorise/EmuDeck/blob/7bd5c10f49de46b50f8081a959feb6e15fb91ba9/functions/EmuScripts/RetroArch_maincfg.sh#L2857

This is completely stupid. I only noticed after I turned on config auto save to ON, changed some things that stayed put after a restart, but start+select kept closing my games.  Please only copy the config on first run/install of EmuDeck. Afterwards it should be up to us. ....

**Comment by Godsbane** [comment]
Not sure what you mean - absolutely doesn't run before launching. Those are used during installation.
