### ISSUE TITLE
Suggestion: Enable VSync by default for PCSX2 (and others emulators ?)

### ISSUE THREAD

**Issue by N3xusPr1me** [dragoonDorise/EmuDeck#244]
Hello, 
I have noticed PCSX2 has VSync disabled using the default Emudeck config. It runs way smoother with VSync and I do think the default config would be better with VSync enabled. Is there a rational behind having it default to off ? What about other emulators (e.g. Cemu defaults to VSync off) ?
Thank you for your truly awesome script !!!

**Comment by Godsbane** [comment]
I'd love to know more about this. do you have any hard examples of how it runs better? I was under the impresion that gamescope didn't care about vsync because it was always forced on.

https://www.reddit.com/r/SteamDeck/comments/t5xubo/why_doesnt_the_steam_deck_have_no_tearing_even/

i am not an expert on this topic, so any more info you can provide i would appreciate.

**Comment by Godsbane** [comment]
No it's very interesting, thank you for taking the time to report it. I will do some testing as well!

**Comment by N3xusPr1me** [comment]
Thank you, keep it up ! At your disposal if you need anything

**Comment by Godsbane** [comment]
For now - i have enabled vsync by default for pcsx2. I tested a bit with burnout 3, and i did see a small reduction in jitter, but that game wasn't bad anyways.

At the very least, it didn't seem to hurt anything.

**Comment by Godsbane** [comment]
Going to close as that went into 0.17.5
Open a new issue if you find more.
