### ISSUE TITLE
Yuzu migration failed, emulator broken

### ISSUE THREAD

**Issue by anaisbetts** [dragoonDorise/EmuDeck#268]
I upgraded Emudeck and it broke my Flatpak Yuzu install during the upgrade to AppImage - here's my log file: https://gist.github.com/anaisbetts/3ff9583ff583a08a0a1f9d9793c0c2e3

**Comment by Godsbane** [comment]
Your log seems to indicate that you had multiple copies of the Emudeck script running.
Please try to run it again, ensuring it only executes once. Sometimes this happens because the default for the deck is Click to Open, and people double click / tap on the icon.

**Comment by Godsbane** [comment]
hi @anaisbetts did that work / help? Once completed, the Yuzu AppImage can be accessed in ~/Applications/yuzu.AppImage

**Comment by anaisbetts** [comment]
Let's just make sure this doesn't happen, give me a second to send in a PR

**Comment by Godsbane** [comment]
Good morning -

I actually already have something similar to this in one of the dev branches. if all goes well, it's going to be merged into main with the next release. 

https://github.com/dragoonDorise/EmuDeck/blob/2985bbe43fa82beace796a9a2645d3c69f7b43f4/install.sh#L8-L34

I recognize this is not helpful for you right now, but we can't merge PR's directly to main. If possible could you rebase to dev? We can evaluate it with the version i linked above. In the mean time, you should be able to run your version of the script locally. It will still pull the required files from our repository.

I do have a Yuzu related question. You mentioned it was broken now, but i don't know what that means. Does it simply not run? One of the merger steps is to copy the data from the flatpak location to the appimage location, and then it symlinks the two directories back. If your flatpak version doesn't have access to the directories we symlinked, it's possible that is making it fail. 

The reason this could be an issue for you, and not for others, is because in later emudeck installs we had been granting the flatpak access to what the user has access to, in an effort to make the yuzu UI entries for opening paths work correctly (which was also hit or miss with the flatpak). If this is the problem, it's a bug i need to address in the installer by adding the appropriate permissions even though we aren't using the flatpak anylonger.

If you would like to discuss further (or in real time) please feel free to jump in our [discord ](https://discord.gg/ZJmGqBkG) and ping me (livedeht)

**Comment by Godsbane** [comment]
Thanks for the update. I would still rerun emudeck based on the log contents, but if you are satisfied and everything seems fine, you can leave it. I'd at least make sure the Tool Updater (shortcut should be on the desktop) works so you can get off cycle updates for tools easily. As we work towards rewriting the whole UI/framework, updates will hopefully be a smoother experience

**Comment by anaisbetts** [comment]
@Godsbane Honestly, I know I'm an edge-case but I would actually prefer it to be entirely command-line, so that I can run it via SSH on my laptop with the non-miniature text :)

**Comment by Godsbane** [comment]
> @Godsbane Honestly, I know I'm an edge-case but I would actually prefer it to be entirely command-line, so that I can run it via SSH on my laptop with the non-miniature text :)

No that's a valid request. Will try to make that doable with the rewrite.
