### ISSUE TITLE
Add "remote play together" to added steam games

### ISSUE THREAD

**Issue by kjv13** [dragoonDorise/EmuDeck#281]
Remote play together is a feature on steam that allows a steam game to be streamed to a friend and their controller inputs are streamed back to the pc. To use this feature it needs to be enabled. If you download retroarch through the steam store for example, this feature is already enabled.

The goal is to add remote play to every game that is added to your stream library via EmuDeck.

This can possibly be done using something like the following
https://github.com/m4dEngi/RemotePlayWhatever

**Comment by Godsbane** [comment]
I looked at that solution, and it's not feasible at this time due to the nature of how the deck works. I'm going to close this issue, and if it ever changes (an AppImage release), we can look at it again. Feel free to reopen if you find another solution that doesn't require builds / updates for every steam client update.
