### ISSUE TITLE
Suggestion: Make relative links when generating roms folder

### ISSUE THREAD

**Issue by MagnusVesper** [dragoonDorise/EmuDeck#288]
In the roms folder, there are a few soft links generated, like "gc" to "gamecube". Those links are made absolute, so you can't just copy the roms folder into a new location. It would be nice if those soft links were relative, so we can copy/move the folder easily.

**Comment by Godsbane** [comment]
i think - you want hard links in the roms directory instead of symbolic links? It should work as long we don't cross filesystems, but the gain here is dubious. We'd need to unlink the ones we have and then relink it all at next install. Plus if this person moved the roms directory, we are just gonna make it again, and point everything back to the folder we made, breaking the whole EmulationStation / SRM setup every time.

**Comment by dragoonDorise** [comment]
I'm sorry but we are not going to implement this suggestion, the symlinks exists just as a way to fix some naming mismatch we had in the past and we will probably eliminate all of them in future releases anyway. Since Thanks for your suggestion though!
