### ISSUE TITLE
How can I change the default core/emulator in emulation station (nds)

### ISSUE THREAD

**Issue by Elektrobrain** [dragoonDorise/EmuDeck#375]
An update changed the nds core, which made my old saves no longer work, I use the emulation station to start
here. Is there a way to change the emulator in a config (from melonds to desmuMe)?

**Comment by Godsbane** [comment]
Hiya, we've exclusively configured melonDS core since the start of the project for NDS. I add this information only so you know where our focus is.

I know an EmulationStation-DE update did change the default at one point, though. You'd want to check the release notes from their repository.

If you want to change EmulationStation-DE's default emulator, you can do so by going to settings, other settings, alternate emulators, but know we haven't done any desmume setup :)

**Comment by Elektrobrain** [comment]
thank you
