### ISSUE TITLE
Emulation Station is showing `.bin` files in addition to `.cue` files in the PSX games list

### ISSUE THREAD

**Issue by spkane** [dragoonDorise/EmuDeck#383]
From the README it looks like `.bin` files should not be showing up in the PSX emulator, but I see both `.cue` and `.bin` files in the EmulationStation game list, which means I have many entries for the same game. 

Where is this set and how would I go about hiding the `.bin` files from the list for PSX games?

I'd be happy to submit a PR, if I can figure out where this is exactly.

**Comment by Godsbane** [comment]
EmulationStation-DE has its own rules set by it's author. For the most part they align with what we've done with steam rom manager, and that's why things work fairly seamlessly between the two. For things such as default emulator, we have set these at install time to line up with what we believe the best experience is.

Bin and cue for psx is a (sort of) contentious subject.  Not everyone uses the cue files, even if it's more correct to have them. If steam rom manager had the ability to skip a bin if a matching cue were found, then we would include bin in the parser there as well.

That all said, there are already ways to handle this issue for EmulationStation-DE.

1) (my personal preference) Convert games from bin and cue to chd. There's a script on the desktop called Emudeck compression tool which can automatically do this. You get some pretty great space saving here on top of one file.

2) use the directory interpreted as file feature in EmulationStation-DE. This will make the files show up once.

Perhaps more ways too that I am not sure of.

Let me know if this helps!

**Comment by Godsbane** [comment]
going to go ahead and close this. Let me know if you want more information or want to discuss further.

**Comment by spkane** [comment]
Thank you for the information @Godsbane . I gave the Emudeck compression tool a test and it worked for many of the games, but about 75% of the Dreamcast games no longer worked so I had to revert to the older images.

I'll look at the directory interpreted as file feature in EmulationStation-DE, and see if I can make use of that as well.

**Comment by Godsbane** [comment]
Sorry to hear that about your Dreamcast roms. It is designed for sets having gdi files, and those without (cue / bin ) are not handled by chdman well. I've been told a newer binary might, so i will do some testing (but i don't ahve any dreamcast roms which don't have gdi files to test with :) )

**Comment by spkane** [comment]
Oh. I think I actually have the gdi files, but had removed them earlier when I was trying to get only one entry to show up, since the games appeared to work just fine without them. I'll add them back in and give the compressor a try again. Thank you for the pointers they have been really helpful!
