### ISSUE TITLE
External controller not recognized on Desktop mode

### ISSUE THREAD

**Issue by Towli** [dragoonDorise/EmuDeck#387]
Booting games through steam in desktop mode (both standard steam and big picture) results in the single external controller not getting recognised, even with controller re-ordering (which does work in gaming mode). Of course this works fine in Emulation station, but wondering if there's some workaround or low hanging fruit for a seamless experience through Steam here?

**Comment by Godsbane** [comment]
because steam uses virtual controllers (through steam input) it's hard to say what may or may not happen in desktop mode as opposed to game mode.

Everything has been mapped to be used in Game mode (as i think this is the expectation of use)

That said, i use xbox controllers in desktop mode all the time for testing stuff  (and i can't think of any where i've had trouble). What specific emulator are you finding is not working?

**Comment by Godsbane** [comment]
closing due to no response, and i've tested in desktop mode quite a bit with an external controller but can't replicate the problem.
