### ISSUE TITLE
Dynamic Input for Dolphin?

### ISSUE THREAD

**Issue by exp111** [dragoonDorise/EmuDeck#395]
Maybe automatically install [this](https://github.com/Venomalia/UniversalDynamicInput) to use dolphin's dynamic input texture feature (which replaces button prompts with ones for the current input device).

Installation only requires to unpack the .rar into the Load directory and enable a option to load custom textures.

**Comment by Godsbane** [comment]
tried it, ended up with a bunch of ? everywhere

**Comment by Godsbane** [comment]
have you tried this, and did you have the same results? I really want this to work, because it's amazing.

**Comment by exp111** [comment]
Probably also relates to https://github.com/Venomalia/UniversalDynamicInput/issues/108

Hadn't tested it before (I just saw a reddit post and hoped/assumed it worked there, but they just added a custom image for some shit).
One problem is that the controller is called `evdev/0/Microsoft X-Box 360 pad 0` (idk if emudeck adds the 0) while the dynamic input only targets ``evdev/0/Microsoft X-Box 360 pad`. Changing the config files to target ... 0, fixes the question marks.
That would at least show xbox controls but we probably want proper steam deck icons, which would need some changes in the other repo

**Comment by Venomalia** [comment]
> tried it, ended up with a bunch of ? everywhere

=>[UniversalDynamicInput Problem-solving](https://github.com/Venomalia/UniversalDynamicInput/wiki/Problem-solving#i-see--buttons)
this means that it did not recognize the buttons, this happens when you use input syntax like **`` `button A`&`button B` ``**.
this also happens when keys are used that are not defined in the pack json. in this case, I will add them if you point them out to me.
when I have time I also take care of steam deck icons, but the whole thing must first work.

**Comment by exp111** [comment]
https://github.com/Venomalia/UniversalDynamicInput/pull/116 added support for the default controller.
That means we could add it - won't have steam deck icons yet though

It's also 300 mb to download

**Comment by Godsbane** [comment]
Awesome I will test this again when I have time. I last tried it quite a while ago, and obviously I should have dug into it more to report the proper inputs to your project, @Venomalia.

I think if we wanted to do this @exp111, we would want to make it an optional download instead of bundling it by default. (only because of size)

There's also another effort to move custom textures to the Emulation/storage path we have setup so that users with small decks don't have to put something like this in their internal storage. I'd probably want to get that sorted first.

As for icons, the steam deck can just use the same icons as the xbox one controllers do (which is what appears to be set up in the repository now). I don't think much(anything?) needs to change here.

> > tried it, ended up with a bunch of ? everywhere
> 
> =>[UniversalDynamicInput Problem-solving](https://github.com/Venomalia/UniversalDynamicInput/wiki/Problem-solving#i-see--buttons) this means that it did not recognize the buttons, this happens when you use input syntax like **`` `button A`&`button B` ``**. this also happens when keys are used that are not defined in the pack json. in this case, I will add them if you point them out to me. when I have time I also take care of steam deck icons, but the whole thing must first work.

**Comment by Venomalia** [comment]
I don't have a steam deck, so I am dependent on problems being reported to me.
the repro is now 300mp but can be reduced to 100mb, and even further to 20mb if you keep only one controller in it.
however, an optional download is the better idea.

**Comment by exp111** [comment]
Yeah optional sounds good. 

You could just symlink the Load folder to the storage folder, which would be easy enough
