### ISSUE TITLE
Uninstalling EmuDeck uninstalled the system wide Yuzu install and deleted my save games

### ISSUE THREAD

**Issue by l0wl3vel** [dragoonDorise/EmuDeck#401]
As far as I can remember EmuDeck ships with its own install of Yuzu and still deleted the flathub version of yuzu and the associated configuration. This might be unintended behaviour.

**Comment by Godsbane** [comment]
@dragoonDorise tagging you to look at the uninstall script for some refinement. 

It's not invalid to remove the flatpak because we also used to install it, but maybe another line to clarify which is getting removed, or that both are getting removed.

To explain at least partially - it depends on when you installed. We used the flatpak for a long while, but found performance was not as good as the AppImage.
With updates we stopped installing the Flatpak and only download and use the AppImage.
There was also a migration that took place that symlinks the two config locations together so that you could use which ever you prefer with the same config and files. (and the same script to launch it even)

**Comment by dragoonDorise** [comment]
It's been a long time since we switched to the app image so we are removing the flatpack uninstallation for Yuzu since we are no longer installing it. This way we prevent to uninstall Yuzu if the users installed it by themselves.

**Comment by dragoonDorise** [comment]
This should be fixed in 2.0.8. Please reopen this if you still find issues!
