### ISSUE TITLE
Cemu 2.0

### ISSUE THREAD

**Issue by bernharl** [dragoonDorise/EmuDeck#402]
Now that Cemu is open source and has a native Linux build, will EmuDeck switch to that version once it gets a (currently planned) Flatpak?

**Comment by NightHammer1000** [comment]
Flatpak is still a very long way off according to the devs. It's also very hard to get a native build to compile and run on steamOS because of its very outdated libraries.

Still better off running the Windows Version

**Comment by Godsbane** [comment]
Yeah this is very much a "We'll change when it's better" situation. The cemu build for linux doesn't even run on the deck (stock) because of missing libraries. I tested the build released last night. 

Short answer is that one day, yes we will migrate when it's worth doing.

It won't be the day it's released, as we need to come up with a migration plan and test. As long as you are using the cemu.sh / mlc01 in the wiiu directory though we should be able to migrate without issue.

**Comment by ViViDboarder** [comment]
For folks tracking this, it looks like there's a PR #505.
