### ISSUE TITLE
EmulationStation name in Gaming mode

### ISSUE THREAD

**Issue by felipecrs** [dragoonDorise/EmuDeck#457]
Currently, when you install everything, the EmulationStation name in Gaming mode (Steam shortcut) is set as _EmulationStation-DE-x64_SteamDeck_, which could have a better name, for example:

_EmulationStation Desktop Edition_
_EmulationStation DE_
_EmulationStation_

I know the name can be (probably) overridden manually in both Steam and in Steam ROM Manager, but I think we can improve the default one.

Pics:

![V1IzF5ml59A-00-06-29](https://user-images.githubusercontent.com/29582865/196448757-0357042b-d577-4102-8d41-40a3cad8f093.png)

**Comment by Godsbane** [comment]
yes i agree - it's something we should fix. Probably the easiest would be wrapping the current one in a shell script and parsing that instead of the actuall appimage. This lets current users leave theirs alone, and new users will get the new name?

Something like this. I'll mark this as an enhancement and we can look at it later.

**Comment by WedgeSparda** [comment]
Yes, please, this would be great.

**Comment by saildot4k** [comment]
Recommend Emulation Station DE or Emulation Station Desktop Edition.
Emulation Station is an older program that is years out of date.

**Comment by dragoonDorise** [comment]
I justo checked and this was fixed a long time ago, closing..
