### ISSUE TITLE
Installing GyroDSU does not enable the service

### ISSUE THREAD

**Issue by Marx1st** [dragoonDorise/EmuDeck#495]
Hi!

I installed GyroDSU with EmuDeck, but Cemu would not detect the controller. One still has to run the script that is mentioned on the project's GitHub page: https://github.com/kmicki/SteamDeckGyroDSU

After doing so (and an additional reboot) Cemu detects the DSU controller.

I propose to run the script when installing GyroDSU from EmuDeck or, at least, inform the users that additional steps are neccessary.

**Comment by Godsbane** [comment]
That's what the step does. ( You can read the code, it's open source )

There's an issue apparently.

**Comment by Marx1st** [comment]
> That's what the step does. ( You can read the code, it's open source )
> 
> There's an issue apparently.

Good that I've opened one, then :)

**Comment by Godsbane** [comment]
This turned out to be an appimage / sudo / terminal issue which is why it was so hard to track down. Everything worked when running manually, but broke from the appimage. To fix it, we've enabled launching the terminal to run the command to install. It's still enter password and go, but it's less than ideal. None the less, should be working with next release.

**Comment by Godsbane** [comment]
Going to close as we actually hotfixed this to live.
