### ISSUE TITLE
[Feature Reques] Togglable Auto load and auto save state with EmuStation

### ISSUE THREAD

**Issue by Tormentor667** [dragoonDorise/EmuDeck#544]
I remember AmberELEC having this feature that lets you enable an auto save and auto load state when you are using EmulationStation and exit a game or restart it. It is very useful if you are in a hurry.

You can simply exit a game through a hotkey and it gets saved and as soon as you load the game again it automatically loads the saved state.

**Comment by Godsbane** [comment]
interestingly - we have this done, I think it just got missed in the UI when we updated to the Electron UI.

**Comment by Tormentor667** [comment]
At least it shouldn't be a big deal to re-add it then :) Maybe you can even think about adding the possibility to choose from an available save-state. AmberELEC does this as well and it is quite useful.

**Comment by Godsbane** [comment]
i don't think we can do that specifically.

**Comment by Tormentor667** [comment]
Not a must-have, just a nice-to-have

**Comment by dragoonDorise** [comment]
@Tormentor667 I'm afraid this is not something we could do, AmberElec and such EmulationStation forks can do it because they have ES embedded on their linux OS. We could theoretically create a State Manager on EmuDeck and launch your games from there, but for that we would need to do some prior work to make the App work on gaming mode.

I¡m closing the issue, thanks for the suggestion though

**Comment by Tormentor667** [comment]
I totally understand that. Thanks for your answer and considering :)
