### ISSUE TITLE
Add Xbox Gamepass Options to remote play

### ISSUE THREAD

**Issue by WingofaGriffin** [dragoonDorise/EmuDeck#698]
See: https://steamdeckhq.com/tips-and-guides/xbox-game-pass-on-steam-deck-cloud-streaming/

Greenlight seems most promising to me

**Comment by Spidy123222** [comment]
Might as well mention this as it's used for remote play with xcloud and home remote streaming. https://github.com/unknownskl/greenlight/releases

I add Greenlightt to my steamdeck via its appimage into the applications directory and I'm able to login and remote to my Xbox and mentions similar thing for Xcode. I currently use the stable release so the name of appimage is different than the betas which says greenlight instead of Xbox-Xcloud. This would be a better thing to support if you want more versatile method.

**Comment by Godsbane** [comment]
#702

**Comment by WingofaGriffin** [comment]
Can someone test and see if Greenlight needs a control profile or any config changes to work optimally on deck from the appimage?

**Comment by WingofaGriffin** [comment]
So it should in theory work fine then with just the steam button for mouse control in the default profile. Beautiful.
