### ISSUE TITLE
Emudeck's Setup doesn't include a option for users to put everything in a folder of their choice.

### ISSUE THREAD

**Issue by dawnbomb** [dragoonDorise/EmuDeck#761]
First, it seems it literally doesn't allow this to begin with.

Secondarily, when installing, i tried simply making a folder inside the home directory and select it for roms. I was thrown an error message saying its a non writable directory, despite that it obvious is because i can create a text file in it.

Emu deck should have a option to install EVERYTHING related to emudeck into ONE folder, such that the user actually knows where everything is, unlike currently where the user has to guess and it's all over the place. I had uninstalled old emudeck to try the new one and stuff was still remaining from the old one even after uninstall, so i don't want some "That isn't necessary" answer, because it obviously is when your uninstaller doesn't work properly. There should be an easy way to both understand where emudeck is for interaction purposes, and to be able to nuke it.

**Comment by dragoonDorise** [comment]
Hi @dawnbomb , the uninstaller of the old EmuDeck 1.0 some bugs so it's possible something stayed back, sorry about that, we fixed that on the new EmuDeck.

It's impossible for EmuDeck to install everything on the same folder because:

- If that folder was on a SD Card, the install time would be really slow ( we've tried that on EmuDeck Windows and it's painfully slow)
- The emulators that are flatpaks are installed on the internal storage by design, we don't want to even try to change a core function of steamOS.

What we do is install everything unrelated to emulators on the Emulation folder, appImage emulators go to the ~/Applications folder and the flatpaks emulators go to ~/.var/app folder.
