### ISSUE TITLE
Quick Actions is kind of tacky, and overall main menu text is space inefficent. 

### ISSUE THREAD

**Issue by dawnbomb** [dragoonDorise/EmuDeck#762]
I think it should be removed in favor of everything inside it being the same dark mode color scheme as everything else.

Aside from being visually somewhat ugly, when the user scrolls down a bit, "Quick Actions" still exists taking up screen space. Further, now "Tools & Stuff" is taking up space. Combined with "Welcome back to EmuDeck" in the right scroll amount it takes of 35% of screen space just with useless text.

Instead, i recommend changing the title bar text to "Welcome back to EmuDeck" then entirely remove thewelcome text, quick action text, and tools & stuff text from the main menu.

Infact, if space is made efficent enough, it's probably possible to make it so the scroll bar is unnecessary and to just display everything on screen at the same time.

**Comment by dragoonDorise** [comment]
Hi @dawnbomb our first take on the design was to try to keep everything always on the first fold of the user so no scrollbars were necessary, but at the end we had to cave in since we area adding more than the Deck's screen can show.

The white design of the Quick Actions is to make then stand up, there's certainly an issue with the Quick Actions text staying when scrolling, we'll fix that.
