### ISSUE TITLE
Backup deleted my saves

### ISSUE THREAD

**Issue by murrant** [dragoonDorise/EmuDeck#777]
I was playing a game and the sd card accidentally got ejected ( I didn't notice).
The emulator eventually hung.  So I restarted it.  The game launched and started a fresh save (it changed the save locations to home/deck).  Backup ran and uploaded the save file.

I noticed the sd card was ejected and that the save location was changed and reset the paths to the sd card.  Upon launching the emulator again, it seems to only have the new save.
I looked at the folder on the sd card and confirmed it only contains the new save.

I looked in my cloud storage and it only contains the new save.  I apparently don't have access to file version history on my provider (Dropbox).  So yeah.  All copies of my save are possibly destroyed.

**Comment by Godsbane** [comment]
Something doesn't add up, the paths don't change or reset from a card ejection.

When the card ejects, the path would simply not exist. This would cause the save backup to fail. When it goes back in, the file would exist again.

A large portion of the saves are on internal in any case, and the saves folder is a symlink.( Which would again, not exist when the card is ejected, so there would be no save to upload. It would not overwrite with a new file.)

I'd suggest you look a bit harder. Because this is a one way backup, no files on your deck would be touched by the backup process.

**Comment by murrant** [comment]
I don't understand what happened. Yuzu is the emulator.
I'm still investigating.

When I look on the SD card in another computer, Emulation/storage/yuzu/nand/user/save/0000000000000000/44855A9914B21C257EAC8F6DD757A825/ exists and has the new bad save, is that supposed to be a symlink?

**Comment by murrant** [comment]
I looked in /home/deck/.local/share/nand/user/  and there are no saves there, only "Contents"

**Comment by Godsbane** [comment]
Yuzu saves are in nand.

Yuzu makes profile folders.

Sometimes yuzu makes "new" profile folders for seemingly no reason.

I'm your example 44855A9914B21C257EAC8F6DD757A825 is your current profile folder. Check if there's another.

**Comment by murrant** [comment]
There are others, Great!  now I just need to figure out how to get back to that profile as it doesn't show up in Yuzu.
ugh, so frustrating.

Sorry for the false bug report and thanks for the help.

**Comment by Godsbane** [comment]
No worries, I totally understand. The yuzu thing gets people in the yuzu discord all the time.

Anyways easiest way imo is to simply figure out your previous profile folder and rename it to the new profile folder, and you are good.
