### ISSUE TITLE
[Feature Request] BIOS Folder Structure Suggestion

### ISSUE THREAD

**Issue by OdinVex** [dragoonDorise/EmuDeck#811]
Having tons of somewhat indistinguishing names for BIOS files (especially since some traditional names overlap, like ROM1.BIN), it might benefit the BIOS folder to also use the same ROM structure for naming.

Examples:
```
bios/psx/SCPH...
bios/ps2/SCPH...
```

It makes it easier to sort out which ones are specific to each emulator, either because an emulator may not filter out names or because you may be developing and testing your own BIOS.

**Comment by Godsbane** [comment]
On the one hand I understand your thoughts on this, regarding folders.

On the other, since we've had documentation out for a year+ on the proper place to put it, it would be counter productive to change suddenly.

The current stance is that all bios directories are mapped to Emulation/bios.

The only folders that are required are required because of some RetroArch cores having requirements outside of the system folder.

I'd be curious as to how  @rawdatafeel and @WingofaGriffin and @dragoonDorise feel about this.

**Comment by Godsbane** [comment]
I'd need some specific examples of this issue, please. Maybe file hashes would be useful.
