### ISSUE TITLE
Recommended approach for sharing Roms directory/device in dual-boot setups

### ISSUE THREAD

**Issue by felipejfc** [dragoonDorise/EmuDeck#816]
So I'm dual booting windows and chimeraos in my ROG Ally and I would like to share the same data/roms folder between both systems. I thought about 2 possible approaches, can you let me know if they would work, or if you recommend another path:

1) Formatting the SD Card in exfat that's supported by both OSes
2) Using software to mount the ext4 partition in windows

If I go for 2, how do I reconfigure my existing installation to point to it? Do I need to reinstall emudeck?

**Comment by Godsbane** [comment]
exfat won't work as we make use of symlinks. your best bet is going to btrfs with the btrfs driver in windows. I believe it is more stable than the ext4 driver. (but don't quote me on this)

the whole scenario is not really supported, since the Emulation folders don't align 100% (due to differences in the systems). I'd also remind you this is specifically not an emudeck-we issue tracker, and as such it's not appropriate to open an issue here.

Emudeck-we is being ported by one person. I'd suggest reaching out to them on the appropriate issue tracker:

https://github.com/EmuDeck/emudeck-we/issues

Make sure that they know the scenario you want to setup for. Remember that WE is not done and is likely to change quite a bit before release, and the Linux version is much further along and more mature.

**Comment by felipejfc** [comment]
thanks for the answer
