### ISSUE TITLE
How do save states work?

### ISSUE THREAD

**Issue by rudtek** [dragoonDorise/EmuDeck#820]
Can I have separate saves in games for separate Steam profiles?  As an example, for switch games, I would love to be able to switch the location that games are saved based on who signed in.  is this possible? If so, how?

**Comment by gotttlieb** [comment]
I just face this issue. But maybe we should rework the question.
Right now, seems that all Savegames are stores in the same folder and are not dependant on the Steam User.
Right now, I'am sharing the device with my patner, but we can't play the same games as for exaple, Yuzu ones.
Maybe it's possible to set a user selector in the start screen and duplicate the saves by user? 
I understand that the problem is that steamdeck is using the same linux user under the hood, and probably that the way the games are saved are not Emudeck related.

Thanks for your work and care!

**Comment by Godsbane** [comment]
User profiles is not something we have coded for at this time. 

That said, yuzu (for example) does let you use multiple user profiles. You can pass a parameter to it when you launch the game.

Not all emulators allow this, unfortunately.
