### ISSUE TITLE
Cloud service prime video uses wrong URL

### ISSUE THREAD

**Issue by bagobones** [dragoonDorise/EmuDeck#826]
The current url points to prime within the regular Amazon market and specifically the US .com

https://www.primevideo.com is just the video player / prime video service and would make a better target, especially for international users.

**Comment by WingofaGriffin** [comment]
@dragoonDorise is European so I imagine they would be able to replicate this?

**Comment by Cederick** [comment]
I'd like to see options for local versions of Prime Video. The currently used and suggested both show a big banner that you can click to get redirected to the .de version since I'm in Germany. I'd love to see EmuDeck using the locale used on the system to determine a preselected domain while you're still able to choose the one you need.
